services:
  postgres:
    image: postgres:16
    container_name: postgres_16_vocagametest
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    networks:
      - db_net

networks:
  db_net:
    driver: bridge